name: Validate Template

on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
  push:
    branches:
      - main
      - master

jobs:
  validate_xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate XML files
        uses: action-pack/valid-xml@v1
        with:
          path: "templates/"
          file-endings: ".xml"
